# Topo version
DEMOV4 = 0
TOPO07 = 1
TOPO_VERSION = TOPO07

# PS as receiver
if(TOPO_VERSION == DEMOV4):
    PS_INDEX = 25-1
elif(TOPO_VERSION == TOPO07):
    PS_INDEX = 7-1
RECEIVER_LOG = 'logs/receiver.log'

# Control plane
READTABLE_TIME = 2
READ_TIME = 60 * 150

# host monitor
AGGRE_MONITOR_TIME = 60 * 150

# test mod
GENERATOR_AND_SEND = 0
TCPREPLAY = 1
MININET_CLI = 2
SEND_MODE = MININET_CLI

# if(SEND_MODE == GENERATOR_AND_SEND), configure:
NGA = 1
SWTICHML = 2
ATP = 3
TEST_MODE = ATP

# if(SEND_MODE == TCPREPLAY), configure:
REPLAY_PCAP_DIR = 'mypcap/2000/'
REPLAY_PCAP_PREFIX_NGA = 'param_NGA-'
REPLAY_PCAP_PREFIX_SWITCHML = 'param_switchML-'
REPLAY_PCAP_PREFIX_ATP = 'param_switchML-' # 共用
REPLAY_PCAP_PREFIX = REPLAY_PCAP_PREFIX_ATP
REPLAY_SPEED = 0.043 # M