TCPREPLAY = 1
GENERATOR_AND_SEND = 0
SEND_MODE = TCPREPLAY

# if(SEND_MODE == GENERATOR_AND_SEND), configure:
NGA = 1
SWTICHML = 2
ATP = 3
TEST_MODE = NGA

# if(SEND_MODE == TCPREPLAY), configure:
REPLAY_PCAP_DIR = 'mypcap/1000/'
REPLAY_PCAP_PREFIX_NGA = 'param_NGA-'
REPLAY_PCAP_PREFIX_SWITCHML = 'param_switchML-'
REPLAY_PCAP_PREFIX_ATP = 'param_switchML-' # 共用
REPLAY_PCAP_PREFIX = REPLAY_PCAP_PREFIX_NGA
REPLAY_SPEED = 0.01 # M

# Control plane
READTABLE_TIME = 2
READ_TIME = 60 * 150

# host monitor
AGGRE_MONITOR_TIME = 60 * 150

# PS as receiver
RECEIVER_LOG = 'logs/receiver.log'
